diverse_prompts = [
    "A firefighter in full gear holding a water hose.",
    "A doctor listening to a patient's heartbeat with a stethoscope.",
    "A chef meticulously plating a gourmet dish in a kitchen.",
    "A construction worker wearing a hard hat at a building site.",
    "A scientist looking through a microscope in a laboratory.",
    "A software engineer typing on a laptop with multiple monitors.",
    "An artist painting on a large canvas in a sunlit studio.",
    "A farmer driving a tractor through a green field.",
    "A musician playing a guitar on a dimly lit stage.",
    "A teacher writing on a chalkboard in front of a classroom.",
    "A police officer directing traffic on a busy street.",
    "A barista pouring latte art into a coffee cup.",
    "A judge sitting at the bench in a courtroom.",
    "A mechanic working under a car in a garage.",
    "A gardener pruning bushes in a well-kept garden.",
    "A pilot in the cockpit of an airplane, preparing for takeoff.",
    "A person reading a book in a cozy armchair.",
    "Two friends playing video games on a couch.",
    "A family having a picnic in a sunny park.",
    "A hiker standing on a mountaintop, looking at the view.",
    "A surfer riding a large wave in the ocean.",
    "A child flying a colorful kite on a windy day.",
    "A group of people practicing yoga in a studio.",
    "A person knitting a scarf with brightly colored yarn.",
    "A photographer taking a picture of a flower.",
    "A couple dancing in a ballroom.",
    "A person fishing by a calm lake at sunrise.",
    "A woodworker carving a piece of wood in a workshop.",
    "A stamp collector examining a stamp with a magnifying glass.",
    "A person building a model airplane.",
    "A group of friends playing board games around a table.",
    "A person meditating in a quiet, serene garden.",
    "A child laughing hysterically while playing.",
    "A person crying silently, tears on their face.",
    "A couple holding hands while walking on a beach.",
    "A group of colleagues in a heated discussion during a meeting.",
    "A surprised person with their mouth wide open.",
    "A look of deep concentration on someone's face.",
    "A hug between two old friends at an airport.",
    "A shy smile from a person looking at the camera.",
    "A crowd of people cheering at a sports event.",
    "A person looking bored and tired at a desk.",
    "A look of fear and suspense on a face.",
    "A parent comforting their crying child.",
    "A look of pure joy and celebration.",
    "A person sitting alone, looking thoughtful and pensive.",
    "A team high-fiving after a victory.",
    "An angry expression, with furrowed brows.",
    "A golden retriever fetching a stick in a park.",
    "A tabby cat sleeping curled up on a soft blanket.",
    "A small hamster running on a wheel inside its cage.",
    "A colorful parrot perched on a person's shoulder.",
    "A goldfish swimming in a clean fishbowl.",
    "A playful kitten chasing a red laser pointer dot.",
    "A pug dog with a wrinkled face looking up.",
    "A white rabbit nibbling on a carrot.",
    "A border collie herding sheep in a field.",
    "A person grooming a long-haired Persian cat.",
    "A turtle slowly crawling on the grass.",
    "A snake coiled inside a glass terrarium.",
    "A lizard basking on a rock under a heat lamp.",
    "A group of puppies tumbling and playing together.",
    "A pet rat climbing on its owner's arm.",
    "A beautiful Siamese cat with bright blue eyes.",
    "A majestic lion resting in the shade on the savanna.",
    "A herd of elephants walking towards a watering hole.",
    "A giraffe eating leaves from a tall acacia tree.",
    "A red fox standing in a snowy forest.",
    "A grizzly bear catching a salmon in a river.",
    "A group of monkeys swinging from vines in the jungle.",
    "A kangaroo with a joey in its pouch.",
    "A wolf howling at the moon.",
    "A deer grazing peacefully in a meadow at dawn.",
    "A zebra standing in a herd, its stripes a confusing pattern.",
    "A polar bear walking on an ice floe.",
    "A rhinoceros with a thick, armored hide.",
    "A squirrel burying nuts in the ground.",
    "A chameleon changing colors on a branch.",
    "A panda chewing on bamboo.",
    "A camel walking across a sand dune in the desert.",
    "A bald eagle soaring high in a clear blue sky.",
    "A colorful toucan sitting on a branch in the rainforest.",
    "A hummingbird hovering next to a red flower.",
    "A flock of penguins waddling on an iceberg.",
    "A great white shark swimming in the deep ocean.",
    "A pod of dolphins leaping out of the water.",
    "A brightly colored clownfish hiding in an anemone.",
    "A majestic blue whale surfacing for air.",
    "An octopus moving along the seafloor.",
    "A sea turtle swimming gracefully over a coral reef.",
    "A flock of flamingos standing in shallow water.",
    "An owl perched on a tree branch at night.",
    "A jellyfish glowing in the dark water.",
    "A starfish attached to a rock in a tide pool.",
    "A swan gliding elegantly across a lake.",
    "A swarm of bees around a hive.",
    "A vast mountain range with snow-capped peaks.",
    "A dense, green rainforest with sunlight filtering through the canopy.",
    "A winding hiking trail through an autumn forest.",
    "A volcano erupting with lava and ash.",
    "A serene alpine lake reflecting the surrounding mountains.",
    "A close-up of moss growing on a tree trunk.",
    "A waterfall cascading down a rocky cliff.",
    "A field of tall pine trees covered in fog.",
    "A rocky canyon carved by a river.",
    "A person standing on a cliff overlooking a deep valley.",
    "A log cabin nestled in a remote forest.",
    "A canopy walk high above the jungle floor.",
    "A forest floor covered in mushrooms and ferns.",
    "The silhouette of mountains against a vibrant sunset.",
    "A narrow gorge with steep, mossy rock walls.",
    "A burnt forest after a wildfire, with new growth.",
    "A pristine tropical beach with white sand and turquoise water.",
    "A powerful ocean wave crashing onto the shore.",
    "A vast, dry desert with rolling sand dunes.",
    "A calm river flowing through a green valley.",
    "A dramatic coastline with cliffs and sea stacks.",
    "A saguaro cactus standing alone in the desert landscape.",
    "A frozen lake in winter, covered in ice.",
    "A vibrant coral reef teeming with colorful fish.",
    "A geyser erupting hot water into the air.",
    "A lightning strike over the ocean during a storm.",
    "An oasis in the desert with palm trees and a small pond.",
    "A sunset over the water, reflecting on the surface.",
    "A wide, muddy river delta seen from above.",
    "A close-up of cracked, dry earth in a drought.",
    "An iceberg floating in the arctic sea.",
    "A view of Earth from space, showing oceans and continents.",
    "A panoramic skyline of a modern city at night.",
    "A narrow cobblestone street in a historic European village.",
    "The Eiffel Tower in Paris on a sunny day.",
    "Modern skyscrapers made of glass and steel.",
    "A traditional Japanese temple with a pagoda roof.",
    "A bustling city square filled with people and fountains.",
    "A run-down, abandoned building with broken windows.",
    "A large suspension bridge, like the Golden Gate Bridge, in fog.",
    "A colorful neighborhood with tightly packed houses.",
    "A grand cathedral with stained glass windows.",
    "A futuristic cityscape with sleek towers.",
    "A suburban house with a white picket fence and a green lawn.",
    "The interior of a grand opera house with red velvet seats.",
    "A minimalist modern home with clean lines and large windows.",
    "An ancient ruin, like the Colosseum in Rome.",
    "A large, complex highway interchange from above.",
    "A yellow taxi cab speeding down a city street.",
    "A person riding a bicycle on a dedicated bike path.",
    "A crowded subway train during rush hour.",
    "A street performer playing music for a small crowd.",
    "A red double-decker bus in London.",
    "A cargo ship loaded with containers in a busy port.",
    "A high-speed bullet train blurring past a station.",
    "A street market bustling with vendors and shoppers.",
    "A motorcycle parked on a sidewalk.",
    "Colorful graffiti art covering a brick wall in an alley.",
    "A person hailing a cab on a rainy night.",
    "A quiet, empty street at dawn.",
    "A hot air balloon festival with many balloons in the sky.",
    "An airplane taking off from a runway.",
    "A classic convertible car driving down a coastal road.",
    "A steam train billowing smoke as it moves on tracks.",
    "A modern, minimalist living room with a grey sofa.",
    "A messy home office with stacks of papers and a laptop.",
    "A cozy bedroom with a neatly made bed and soft lighting.",
    "A bright, clean kitchen with stainless steel appliances.",
    "A child's playroom filled with colorful toys.",
    "An open-plan office with rows of cubicles.",
    "A formal dining room set for a dinner party.",
    "A quiet study with floor-to-ceiling bookshelves.",
    "A person working from home at a cluttered kitchen table.",
    "A baby's nursery with a crib and changing table.",
    "A home gym with weights and a treadmill.",
    "A spiral staircase in a modern house.",
    "A close-up of a houseplant on a windowsill.",
    "A fireplace with a crackling fire.",
    "A minimalist desk setup with a computer and a single plant.",
    "A window looking out onto a rainy day.",
    "The inside of a vast, modern art museum.",
    "A crowded shopping mall during the holidays.",
    "A quiet, grand library with long tables and green lamps.",
    "A busy airport terminal with people and luggage.",
    "A high-end restaurant with white tablecloths.",
    "A supermarket aisle stocked with fresh produce.",
    "A university lecture hall filled with students.",
    "The interior of a historic church with pews.",
    "A bowling alley with people mid-game.",
    "A factory assembly line in operation.",
    "A hospital waiting room with empty chairs.",
    "A concert hall with an orchestra on stage.",
    "A busy post office counter with a line of people.",
    "A gym filled with people exercising on machines.",
    "A science museum with a dinosaur skeleton exhibit.",
    "A crowded subway station platform.",
    "A close-up of a juicy cheeseburger with fries.",
    "A colorful, fresh garden salad in a white bowl.",
    "A steaming hot pizza topped with pepperoni.",
    "A box of assorted chocolates.",
    "A cup of black coffee with steam rising from it.",
    "A sushi platter with various types of maki and nigiri.",
    "A loaf of freshly baked crusty bread.",
    "A slice of birthday cake with a lit candle.",
    "A bowl of vibrant red strawberries.",
    "A glass of red wine being poured.",
    "A traditional Thanksgiving dinner table.",
    "A simple bowl of ramen noodles with an egg.",
    "An ice cream cone with three different scoops.",
    "A stack of pancakes drizzled with maple syrup.",
    "A basket of various fruits and vegetables.",
    "A grilled cheese sandwich being pulled apart.",
    "A sleek, modern laptop open on a wooden desk.",
    "A vintage film camera on a leather strap.",
    "A person holding a new smartphone, screen glowing.",
    "A close-up of a complex computer motherboard.",
    "A white drone flying in the sky.",
    "A pair of over-ear headphones on a table.",
    "A complex set of gears and cogs in a machine.",
    "A rusty hammer and nails on a workbench.",
    "A telescope pointed at the night sky.",
    "A collection of old, obsolete technology like floppy disks.",
    "A futuristic robot assistant.",
    "A virtual reality headset being worn by a user.",
    "A simple pocket knife with multiple tools.",
    "A drawing compass and protractor on graph paper.",
    "A studio microphone on a stand.",
    "A security camera mounted on a wall.",
    "A pair of worn-out blue jeans.",
    "A red high-heeled shoe on a reflective surface.",
    "A mannequin wearing a fashionable dress in a store window.",
    "A comfortable, overstuffed armchair by a window.",
    "A pair of colorful running shoes.",
    "A collection of folded silk scarves.",
    "A heavy wool winter coat on a hanger.",
    "A simple wooden stool.",
    "A baby's onesie hanging on a clothesline.",
    "A dark business suit on a hanger.",
    "An antique grandfather clock.",
    "A modern, glass-topped coffee table.",
    "A pair of round spectacles on top of a book.",
    "A warm, knitted wool sweater.",
    "A simple, plain white t-shirt.",
    "A straw hat on a beach chair.",
    "An abstract painting with chaotic splashes of color.",
    "A close-up of the texture of rough tree bark.",
    "A minimalist black and white photograph of a shadow.",
    "A macro shot of water droplets on a green leaf.",
    "A pattern of colorful mosaic tiles.",
    "A sculpture made of recycled metal materials.",
    "A digital art piece showing geometric shapes.",
    "The texture of smooth, polished marble.",
    "A surrealist painting of a clock melting.",
    "A close-up of woven fabric fibers.",
    "A blurry image of city lights at night (bokeh).",
    "A drawing of a complex, symmetrical mandala.",
    "A conceptual image representing 'connection' or 'networks'.",
    "The iridescent scales of a fish.",
    "A perfectly symmetrical pattern in nature, like a snowflake.",
    "A blank white canvas on an easel.",
    "A massive outdoor music festival with a crowd and stage lights.",
    "A traditional wedding ceremony with a couple exchanging vows.",
    "A vibrant parade float moving down a city street.",
    "A chaotic New Year's Eve celebration with fireworks.",
    "A solemn military funeral with folded flags.",
    "A child blowing out candles on a birthday cake at a party.",
    "A university graduation ceremony with students in caps and gowns.",
    "A religious procession walking through a street.",
    "A costumed Halloween party.",
    "A family gathered around a table for a holiday feast.",
    "A political rally with a speaker and a large crowd.",
    "A crowded carnival with rides and game booths.",
    "A football stadium during a championship game.",
    "A basketball player dunking the ball.",
    "A Formula 1 car racing on a track.",
    "Two chess players intensely focused on a game board.",
    "A marathon runner crossing the finish line.",
    "A gymnast performing on the balance beam.",
    "A professional e-sports team competing in an arena.",
    "A tennis player serving the ball.",
    "A skier speeding down a steep mountain slope.",
    "A group of rock climbers scaling a sheer cliff face.",
    "A swimmer diving into a pool at the start of a race.",
    "A boxer in a ring during a match.",
    "A stunning nebula in deep space, captured by a telescope.",
    "A detailed microscopic image of a living cell.",
    "The double-helix structure of a DNA molecule.",
    "A view of the planet Saturn and its rings.",
    "A diagram illustrating the water cycle.",
    "A high-energy particle collision in a particle accelerator.",
    "A fossil embedded in rock.",
    "The surface of Mars with a rover.",
    "A visualization of a complex protein structure.",
    "A weather satellite orbiting the Earth.",
    "A Petri dish with bacteria cultures.",
    "The rings of a tree trunk, showing its age.",
    "A busy highway road sign with multiple destinations.",
    "A complex infographic with charts and graphs.",
    "An ancient Egyptian hieroglyph carved in stone.",
    "A close-up of a page from a printed book.",
    "A neon sign glowing in a dark window.",
    "A map of a subway system.",
    "The 'on/off' power symbol on a button.",
    "A blank musical score with staves.",
    "A QR code on a product.",
    "A company's logo on a building.",
    "A piece of elegant calligraphy.",
    "A simple 'STOP' sign at an intersection.",
    "A dramatic tornado funnel touching down in a field.",
    "A powerful lightning bolt striking the ground.",
    "The Aurora Borealis (Northern Lights) in the night sky.",
    "Dense, thick fog rolling over a hill.",
    "A close-up of delicate snowflakes on a dark surface.",
    "A vibrant, complete rainbow after a storm.",
    "Dark, ominous storm clouds gathering.",
    "Hailstones covering the ground.",
    "A waterspout forming over the ocean.",
    "Sunlight streaming through clouds (crepuscular rays).",
    "A sandstorm in the desert.",
    "A clear, star-filled night sky (the Milky Way).",
    "A medieval knight in full armor on a horse.",
    "A black-and-white photo of a 1920s city street.",
    "A scene of an ancient Roman forum with people in togas.",
    "A World War II-era soldier in a trench.",
    "A 1950s diner with a jukebox and checkerboard floor.",
    "A Victorian-era street scene with horse-drawn carriages.",
    "Pioneers traveling in a covered wagon.",
    "A grand ballroom dance from the 18th century.",
    "A sepia-toned portrait of a family from the early 1900s.",
    "Vikings rowing a longship.",
    "A 1980s office with bulky computers.",
    "A Stone Age person painting on a cave wall."
]
