dataset_name: celeba
dataset_path: ./data/CelebA
task: retrieval
retrieval_K: 500
query_type: stereotype
bias_attribute: gender
model_ID: RN101
method: roboshot
normalize: true
reject_harmful: true
accept_helpful: true
