dataset_name: celeba
dataset_path: ./data/CelebA
task: retrieval
retrieval_K: 500
query_type: hair
bias_attribute: gender
model_ID: ViT-L/14@336px
method: sem
sem_version: SEM_b
normalize: true
sae_weights_path: debiasing_methods/sae_weights/MSAE_ViT-L-14_768_16384_256x512_reverse.pth
