dataset_name: fairface
dataset_path: ./data/FairFace
task: retrieval
retrieval_K: 500
query_type: stereotype
bias_attribute: gender
model_ID: RN101
method: bendsem
sem_version: SEM_bi
normalize: true
sae_weights_path: debiasing_methods/sae_weights/MSAE_RN101_512_16384_128x256x512_reverse.pth
num_neighbors: 100
