bias_attribute: gender
dataset_name: fairface
dataset_path: ./data/FairFace
hidden_num: 2
method: zsdebias
model_ID: ViT-L/14@336px
normalize: false
query_type: stereotype
retrieval_K: 500
seed: 2
task: retrieval
