dataset_name: fairface
dataset_path: ./data/FairFace
task: retrieval
retrieval_K: 500
query_type: stereotype
bias_attribute: gender
model_ID: ViT-B/16
method: sem
sem_version: SEM_b
normalize: true
sae_weights_path: debiasing_methods/sae_weights/MSAE_ViT-B-16_512_16384_256x512_reverse.pth
