bias_attribute: race
dataset_name: fairface
dataset_path: ./data/FairFace
hidden_num: 2
method: zsdebias
model_ID: RN50
normalize: false
query_type: stereotype
retrieval_K: 500
seed: 2
task: retrieval
