bias_attribute: race
dataset_name: utkface
dataset_path: ./data/UTKFace
hidden_num: 2
method: zsdebias
model_ID: RN101
normalize: false
query_type: stereotype
retrieval_K: 500
seed: 0
task: retrieval
