dataset_name: utkface
dataset_path: ./data/UTKFace
task: retrieval
retrieval_K: 500
query_type: stereotype
bias_attribute: race
model_ID: RN50
method: roboshot
normalize: true
reject_harmful: true
accept_helpful: true
