dataset_name: waterbirds
dataset_path: ./data/Waterbirds
task: zs_classification
class_setting: waterbirds
model_ID: ViT-B/16
method: bendsem
sem_version: SEM_bi
normalize: true
sae_weights_path: debiasing_methods/sae_weights/MSAE_ViT-B-16_512_16384_256x512_reverse.pth
num_neighbors: 100
